config/routes.rb
Rails.application.routes.draw do
  
  root 'tools#home'
  
  get '/reset_pdfs', to: 'pdfs#reset_pdfs'
  get '/import_pdfs', to: 'pdfs#import_pdfs'
  get '/download_pdf/:id', to: 'pdfs#download_pdf'
  get '/new_distill_pdf', to: 'pdfs#new_distill_pdf'
  post '/distill_pdf', to: 'pdfs#distill_pdf'

  resources :companies, :contacts, :tools, :pdfs, :docs, :picture_uploaders

  # get '/bookmarks', to: 'tools#bookmarks'
  # get '/test', to: 'tools#test'
  # get '/import_new_companies', to: 'tools#import_new_companies'
  # get '/trunc_reset', to: 'tools#trunc_reset'
end

app/models/contact.rb
class Contact < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :company

  def short_name
    self.username
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  
  def detail
    contact = Contact.find_by_id(params[:id])
    render plain: contact.username
  end

  def index
    @contacts = Contact.all
    # render 'contacts/index', layout: false
    # render layout: false
    # render json: @contacts
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @contacts }
    end
  end

  def show
    @contact = Contact.find_by_id(params[:id])
    # render 'contacts/show', layout: false
    # render layout: false
    # render json: @contact
     respond_to do |format|
      format.html { render :show }
      format.json { render json: @contact }
    end
  end

  def new
    @contact = Contact.new
    # @company = Company.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:message] = 'Contact created.'
      redirect_to contact_path(@contact)
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find_by_id(params[:id])
  end

  def update
    @contact = Contact.find_by_id(params[:id])
    @contact.update(contact_params)
    if @contact.save
      flash[:message] = 'Contact updated.'
      redirect_to contact_path(@contact)
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find_by_id(params[:id])
    @contact.destroy
    redirect_to root_path
  end

  private
  def set_contact
    @contact = Contact.find_by_id(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:company_id, :username, :email, :password, :image)
  end
end

app/views/contacts/_contact.html.erb
<button class="js-username", data-id="<%= contact.id %>", data-username="<%= contact.username %>">Show username again</button>
<div id="username-<%= contact.id %>"></div><br>

<button class="js-email", data-id="<%= contact.id %>", data-email="<%= contact.email %>">Show Email</button>
<div id="email-<%= contact.id  %>"></div><br>

<button class="js-password", data-id="<%= contact.id %>", data-pw="<%= contact.password %>">Show Password</button>
<div id="pw-<%= contact.id  %>"></div><br>

<button class="js-liame", data-id="<%= contact.id %>", data-liame="<%= contact.email.upcase.reverse  %>">Email reversed in CAPS: </button>
<div id="liame-<%= contact.id %>"></div>
<hr>

<button class="js-image", data-id="<%= contact.id %>", data-image="<%= contact.image %>">Show contact image</button>
 
<hr>

<iframe id="image-<%= contact.id %> src="<%= contact.image %>"></iframe>

app/views/contacts/_image.html.erb
<iframe src="<%= image_tag contact.image %>"></iframe>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>
<%= form_for @contact do |f| %>  
  <p>
    <%= f.label :company %>
    <%= f.collection_select :company_id, Company.all, :id, :name %>
  </p>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p> 
  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p> 
  <p>
    <%= f.hidden_field(:image_cache) %>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p> 
<%= f.submit %>
<% end %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<table>
  <th class="col-large">
    <h3><tr align="left">
      <td>company</td>
      <td>username</td>
      <td>email</td>
    </tr></h3>
  </th>
<% @contacts.each do |contact| %>
  <tr>
    <td><%= link_to contact.company.name, company_path(contact.company_id) %></td>
    <td><%= link_to contact.username, contact_path(contact) %></td>
    <td><%= contact.email %></td>
  </tr>
<% end %>
</table>

app/views/contacts/index.js.erb
// $(function(){
  var html = "<%= j(render(partial: 'contacts/contacts', locals: { contacts: @contacts })) %>";
  var msg = "<h1>The contacts partial, brought to you by AJAX!!</h1>"
  $("div#ajax-contacts").html(msg+html) 
// })
 

app/views/contacts/new.html.erb
<h1>New Contact</h1>
<%= form_for @contact do |f| %>
  <p>
    <%= f.label :company %>
    <%= f.collection_select :company_id, Company.all, :id, :name %>
  </p>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p> 
  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p> 
  <p>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p> 
<%= f.submit %>
<% end %>

app/views/contacts/show.html.erb
<h1>Show Contact</h1>

<h3><%= @contact.id %>: <%= @contact.username %></h3>
<p><%= @contact.email %></p>
<p><%= link_to @contact.company.name, company_path(@contact.company) %></p>
<p><%= @contact.company.about %></p>

<img src="<%= @contact.image %>">
<div id="body-<%= @contact.id %>"></div>

<%= render partial: 'contacts/contact', locals: { contact: @contact }%>
 
<script type="text/javascript" charset="utf-8">
$(function(){
 

  $(".js-username").on("click", function(){
    var id = $(this).data("id");
    var username = $(this).data("username");
    $.get("/contacts/" + id + ".json", function(data) {
      $("#username-" + id).text(username);
    });
  }); 

  $(".js-email").on("click", function(){
    var id = $(this).data("id");
    var email = $(this).data("email");
    $.get("/contacts/" + id + ".json", function(data) {
      $("#email-" + id).text(email);
    });
  }); 

  $(".js-password").on("click", function(){
    var id = $(this).data("id");
    var password = $(this).data("pw");
    $.get("/contacts/" + id + ".json", function(data) {
      $("#pw-" + id).text(password);
    });
  }); 

  $(".js-liame").on("click", function(){
    var id = $(this).data("id");
    var liame = $(this).data("liame");
    $.get("/contacts/" + id + ".json", function(data) {
      $("#liame-" + id).text(liame);
    });
  });

  $(".js-image").on("click", function(){
    var id = $(this).data("id");
    var image = $(this).data("image");
    $.get("/contacts/" + id + ".json", function(data) {
      $("#image-" + id).text(image);
    });
  });
});  
</script>