config/routes.rb
Rails.application.routes.draw do
  
  root 'tools#home'
  
  get '/reset_pdfs', to: 'pdfs#reset_pdfs'
  get '/import_pdfs', to: 'pdfs#import_pdfs'
  get '/download_pdf/:id', to: 'pdfs#download_pdf'
  get '/new_distill_pdf', to: 'pdfs#new_distill_pdf'
  post '/distill_pdf', to: 'pdfs#distill_pdf'

  resources :companies, :contacts, :tools, :pdfs, :docs, :picture_uploaders

  # get '/bookmarks', to: 'tools#bookmarks'
  # get '/test', to: 'tools#test'
  # get '/import_new_companies', to: 'tools#import_new_companies'
  # get '/trunc_reset', to: 'tools#trunc_reset'
end

app/views/layouts/_admin_nav.html.erb
<div class="container">
  <%= link_to "Pdfs", pdfs_path %> | 
  <%= link_to "Reset Pdfs", reset_pdfs_path %> | 
  <%= link_to "Import Pdfs", import_pdfs_path %> | 
  <%= link_to "Add pdf", new_pdf_path %>
 </div>

app/views/layouts/_main_nav.html.erb
<div class="container">
  <%= link_to "Contacts", contacts_path %> | 
  <%= link_to "New contact", new_contact_path %> |
  <%= link_to "Companies", companies_path %> | 
  <%= link_to "New company", new_company_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabRat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'tools' %>
  </head>
  <body>
    <div class="container">
      <div align="left">
      <hr>
      <%= render partial: 'layouts/main_nav' %>
      <hr>
      <%= render partial: 'layouts/admin_nav' %>
      <hr>
      <%= yield %>
      </div>
    </div>
  </body>
</html>